# Generated by Django 2.0 on 2018-01-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePicture', models.ImageField(default='C:/Users/Varun/Desktop/Images/defaultpicture.png', upload_to='C:/Users/Varun/Desktop/Images')),
                ('userName', models.CharField(max_length=25)),
                ('userDay', models.IntegerField()),
                ('userMonth', models.IntegerField()),
                ('userYear', models.IntegerField()),
                ('userAddress', models.TextField()),
                ('userEmail', models.CharField(max_length=25)),
                ('userPhno', models.BigIntegerField()),
                ('userUname', models.CharField(max_length=25)),
                ('userPwrd', models.CharField(max_length=25)),
            ],
        ),
    ]
