# Generated by Django 2.0 on 2018-01-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20180110_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='userProfilePicture',
            field=models.ImageField(default='C:/Users/varun/Desktop/Images/defaultpicture.png', upload_to='C:/Users/varun/Desktop/Images/'),
        ),
    ]
