# Generated by Django 2.0 on 2018-01-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_driver_info_driverdaylic'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_info',
            name='driverLicensePicture',
            field=models.ImageField(default='C:/Users/varun/Desktop/Images/defaultpicture.png', upload_to='C:/Users/varun/Desktop/Project/garbagemanagement/LicenseImages/'),
        ),
    ]
