# Generated by Django 2.0 on 2018-02-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20180212_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('driverId', models.IntegerField()),
                ('combination', models.IntegerField()),
                ('tempAddress', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='driver_info',
            name='driverDayDOB',
        ),
        migrations.RemoveField(
            model_name='driver_info',
            name='driverMonthDOB',
        ),
        migrations.RemoveField(
            model_name='driver_info',
            name='driverYearDOB',
        ),
    ]
