# Generated by Django 2.0 on 2018-03-02 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20180223_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver_info',
            name='driverAddress',
        ),
    ]
