# Generated by Django 2.0 on 2018-03-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_remove_schedule_driver_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='driver_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
