# Generated by Django 2.0 on 2018-03-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_auto_20180314_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='isLoggedIn',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
