# Generated by Django 2.0 on 2018-03-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_auto_20180319_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garbagedetails',
            name='garbagePicture',
            field=models.ImageField(default='C:/Users/Deeraj Ramchandani/Desktop/Images/defaultpicture.png', upload_to='C://Users/varun/Desktop/Project/garbagemanagement/UserImages'),
        ),
        migrations.AlterField(
            model_name='garbagedetails',
            name='garbagePictureVerification',
            field=models.ImageField(blank=True, default='C:/Users/Deeraj Ramchandani/Desktop/Images/defaultpicture.png', null=True, upload_to='C://Users/varun/Desktop/Project/garbagemanagement/UserImages'),
        ),
    ]
